### PR TITLE
Revert "I have implemented the add and get function"

### PR DESCRIPTION
**Pull request by MayThetNaingBo**
Reverts MayThetNaingBo/foodblog-dvops#2

### CODE REVIEW

**Comment by MayThetNaingBo** [comment]
I have created a new pull request

**Comment by MayThetNaingBo** [comment]
I have created a new pull request

**Comment by IGIngyin** [comment]
This looks better.

**Comment by IGIngyin** [comment]
I have seen the changes. Thank you.

**Comment by MayThetNaingBo** [comment]
Then I will merge

**Pull request merged**
