### PR TITLE
I have implemented the add and get function

### PR DESCRIPTION
**Pull request by MayThetNaingBo**
I will try to keep the data remained when the page is refreshed

### CODE REVIEW

**Comment by IGIngyin** [comment]
This looks better

**Comment by tashi-ihsat** [comment]
better now

**Comment by tashi-ihsat** [comment]
How about you the create post goes to next page instead of pop-up for better user interface

**Comment by MayThetNaingBo** [comment]
@tashi-ihsat Oki I will try

**Pull request merged**
